--- 
 
- llm_platform: OpenAI
  gpt-4o:
    token_limit: 4096
    system_delimiter: '### '
    user_delimiter: '### '
    delay: 0
    temperature: 0

  gpt-4-turbo:
    token_limit: 4096
    system_delimiter: '### '
    user_delimiter: '### '
    delay: 0
    temperature: 0

- llm_platform: Meta
  llama3-70b-8192:
    token_limit: 131072
    system_delimiter: '### '
    user_delimiter: '### '
    delay: 70
    temperature: 0

  llama-3.1-70b-versatile:
    token_limit: 131072
    system_delimiter: '### '
    user_delimiter: '### '
    delay: 70
    temperature: 0

- llm_platform: Google
  gemini-1.5-pro-latest:
    token_limit: 131072
    max_output_tokens: 251072
    system_delimiter: '### '
    user_delimiter: '### '
    delay: 40
    temperature: 0
    top_p: 0.95
    top_k: 64

- llm_platform: Google
  gemini-1.5-flash:
    token_limit: 131072
    max_output_tokens: 251072
    system_delimiter: '### '
    user_delimiter: '### '
    delay: 40
    temperature: 0
    top_p: 0.95
    top_k: 64
